### ISSUE TITLE
Syntax error + unknown markdown

### ISSUE THREAD

**Issue by Cobwebster** [GatsbyCentral/gatsby-awesome-pagination#14]
Hey, I'm confused as to why this isn't working, it just doesn't render my pages. For starters the documents say use this import

import { paginate } from 'gatsby-awesome-pagination'; in the nodeJs file then when I do I get this error,

import { paginate } from 'gatsby-awesome-pagination'; ^ SyntaxError: Unexpected token {

This is my exports in nodeJs

https://hastebin.com/qigexojeme.php

This is what I put in my component

export const pageQuery = graphql`` query ($skip: Int!, $limit: Int!) { allMarkdownRemark( sort: { fields: [frontmatter___date], order: DESC } skip: $skip limit: $limit ) }

which throws this error-

error GraphQL Error Encountered 1 error(s):

Unknown field 'allMarkdownRemark' on type 'Query'.
https://hastebin.com/ojeduzaniv.xml

-- Seems like the documentation missed out important steps? Or did I just overlook something. I know I probably have nothing defined as "allMarkdownRemark", how would I do that? The tutorial just ignores that part.

**Comment by chmac** [comment]
Looks like your error is unrelated to this plugin. Check the GraphiQL explorer on the Gatsby instance to see what's going on and why you don't have a `allMarkdownRemark` field.
