### ISSUE TITLE
The gatsby documentation is missing npm command to install

### ISSUE THREAD

**Issue by amouratoglou** [GatsbyCentral/gatsby-awesome-pagination#15]
on https://www.gatsbyjs.org/packages/gatsby-awesome-pagination/?=awese
it is missing the npm command to install, all other plugins have them. just that. 
maybe this is not the place to post this? then, sorry.

**Comment by chmac** [comment]
Not sure why that is, maybe something on the Gatsby docs side. Feel free to submit a PR if it should be added to our README.
