### ISSUE TITLE
Int! vs Int in demo docs

### ISSUE THREAD

**Issue by kpennell** [GatsbyCentral/gatsby-awesome-pagination#17]
![image](https://user-images.githubusercontent.com/1060385/62632336-9c1a8d80-b932-11e9-8aa2-e0305b651fc2.png)

Hey there, in the [gatsby plugins](https://www.gatsbyjs.org/packages/gatsby-awesome-pagination/?=paginat), it says ` query ($skip: Int!, $limit: Int!) {` but I noticed several people had no exclamation points. e.g. https://github.com/cpg7023/deploy-web/blob/9e0d64b1c142b3cb7e89bd77f686df3d17255ecc/src/pages/blog.js#L43

Removing ! fixed it for me. What's the difference?

**Comment by chmac** [comment]
Removing the `!` means that the `$skip` and `$limit` field are optional. It’s been a while since we worked on this project, but my memory is that these fields should be required, otherwise there’s probably something not working...
