### ISSUE TITLE
One extra blank paginated page is generated for each tag

### ISSUE THREAD

**Issue by i-bsd** [GatsbyCentral/gatsby-awesome-pagination#42]
If there are 6 pages of posts under a tag, `gatsby-awesome-pagination` generates 7 pages.

Why is that?

How can I change this to render numberOfPages - 1?

**Comment by chmac** [comment]
@i-bsd Can you post a reproduction?

**Comment by sjelfull** [comment]
I have the same issue. 

I have set the `itemsPerPage` to 9, and only have 7 items. It still generates an extra page.

**Comment by chmac** [comment]
@sjelfull Can you post a reproduction?

**Comment by chmac** [comment]
Closing this pending a reproduction, feel free to reopen with a reproduction.
