### ISSUE TITLE
Support gatsby v3

### ISSUE THREAD

**Issue by dasjo** [GatsbyCentral/gatsby-awesome-pagination#52]
**Is your feature request related to a problem? Please describe.**
Currently, this plugin doesn't run with gatsby v3.

**Describe the solution you'd like**
Support for gatsby v3 would be great

**Comment by chmac** [comment]
Can you be more specific about what doesn't work with the latest Gatsby version?

I saw your PR that updates the `peerDependencies`. I guess that change will introduce whatever issue you have currently to anybody using an older version of Gatsby?

**Comment by tailic** [comment]
I also gave it a try and after updating to gatsby v3 none of the paginated pages are being generated when _building_ the project it works when starting the development server.

**Comment by nightOwlNico** [comment]
I am seeing this when running `npm i gatsby-awesome-pagination`:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gatsby-starter-default@0.1.0
npm ERR! Found: gatsby@3.1.2
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^3.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^2.0.0" from gatsby-awesome-pagination@0.3.6
npm ERR! node_modules/gatsby-awesome-pagination
npm ERR!   gatsby-awesome-pagination@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```
It seems like my error is because of this issue

**Comment by chmac** [comment]
I think the solution is likely to add support for Gatsby 3 as a peerDependency, without removing support for Gatsby v2. I'll try to find time to do that this week, also happy to merge a PR that does this, especially if somebody can test it with Gatsby 3.
