### ISSUE TITLE
How To Paginate First Page Differently 

### ISSUE THREAD

**Issue by ryanwiemer** [GatsbyCentral/gatsby-awesome-pagination#6]
@chmac ,

Do you have any thoughts on how to achieve a different number of posts on the first page vs other paginated pages? In a perfect world it would be an additional option such as `itemsPerFirstPage`. 

It's pretty common to see something like the home page with a smaller number of posts while the paginated pages show more. So for example 3 posts on the homepage but then 9 posts per subsequent paginated page.

**Comment by chmac** [comment]
Oooh, super interesting use case. Hadn't thought at all about that. I'm open to adding such an option. It will add a little complexity I think, I'll contemplate on it a few days and see what comes up.

**Comment by ryanwiemer** [comment]
@chmac Sounds good!

In case it's helpful I was able to achieve the desired functionality albeit I had to do the pagination logic manually without the plugin. It's a little messy but it works:

* [`gatsby-node.js`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/paginate/gatsby-node.js#L24-L53)
* [Demo](https://5b9c44d2b13fb161c2d09abd--gcn.netlify.com/)

**Comment by chmac** [comment]
@ryanwiemer Thanks. That’s definitely helpful. I was thinking of calculating the number of pages with slightly different logic, and then doing something like `limit = page === 0 ? postsPerFirstPage : postsPerPage`. Will contemplate further and get back next week.

**Comment by ryanwiemer** [comment]
Cool. Yeah, I'm sure there are better ways to simplify the logic. Like I said it's a little messy right now. 😉

**Comment by chmac** [comment]
@ryanwiemer Wow, it's more complicated than I first though. I forgot to update the `$skip` parameter. I think I've covered that now and I've done some light testing. But will let this sit for a few days and look at it again before releasing.

**Comment by chmac** [comment]
It's out as v 0.3.0. I forgot to look at your bug in #7 before releasing. Will do that now.
